version: '3'
services:
  nginx:
    ports:
      - "8000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE-ENV=development
      - MONGO_USER=jhony
      - MONGO_PASS=mypassword
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jhony
      - MONGO_INITDB_ROOT_PASSWORD=mypassword