version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - node-app
  node-app:
    environment:
      - PORT=8000
    depends_on:
      - mongo
      - redis 
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db: